//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelCompare.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FileOffersPath {
            get {
                return ((string)(this["FileOffersPath"]));
            }
            set {
                this["FileOffersPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FileStocksPath {
            get {
                return ((string)(this["FileStocksPath"]));
            }
            set {
                this["FileStocksPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FileResultsPath {
            get {
                return ((string)(this["FileResultsPath"]));
            }
            set {
                this["FileResultsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EanOffers {
            get {
                return ((int)(this["EanOffers"]));
            }
            set {
                this["EanOffers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int QuantityPackagingOffers {
            get {
                return ((int)(this["QuantityPackagingOffers"]));
            }
            set {
                this["QuantityPackagingOffers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int QuantityOnPalletOffers {
            get {
                return ((int)(this["QuantityOnPalletOffers"]));
            }
            set {
                this["QuantityOnPalletOffers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PriceNettoOffers {
            get {
                return ((int)(this["PriceNettoOffers"]));
            }
            set {
                this["PriceNettoOffers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PriceNettoStocks {
            get {
                return ((int)(this["PriceNettoStocks"]));
            }
            set {
                this["PriceNettoStocks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int QuantityStocks {
            get {
                return ((int)(this["QuantityStocks"]));
            }
            set {
                this["QuantityStocks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EanStocks {
            get {
                return ((int)(this["EanStocks"]));
            }
            set {
                this["EanStocks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddOrderIfQuantity {
            get {
                return ((bool)(this["AddOrderIfQuantity"]));
            }
            set {
                this["AddOrderIfQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AddOrderIfQuantityNumber {
            get {
                return ((int)(this["AddOrderIfQuantityNumber"]));
            }
            set {
                this["AddOrderIfQuantityNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddOwnQuantity {
            get {
                return ((bool)(this["AddOwnQuantity"]));
            }
            set {
                this["AddOwnQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AddOwnQuantityNumber {
            get {
                return ((int)(this["AddOwnQuantityNumber"]));
            }
            set {
                this["AddOwnQuantityNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddQuantityToPalet {
            get {
                return ((bool)(this["AddQuantityToPalet"]));
            }
            set {
                this["AddQuantityToPalet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddQuantityToPackaging {
            get {
                return ((bool)(this["AddQuantityToPackaging"]));
            }
            set {
                this["AddQuantityToPackaging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddProductsWithoutZEroQuantity {
            get {
                return ((bool)(this["AddProductsWithoutZEroQuantity"]));
            }
            set {
                this["AddProductsWithoutZEroQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddOrderIfPriceBaseHigher {
            get {
                return ((bool)(this["AddOrderIfPriceBaseHigher"]));
            }
            set {
                this["AddOrderIfPriceBaseHigher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EanNameOrder {
            get {
                return ((string)(this["EanNameOrder"]));
            }
            set {
                this["EanNameOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OrderNameOrder {
            get {
                return ((string)(this["OrderNameOrder"]));
            }
            set {
                this["OrderNameOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddProductsWithoutName {
            get {
                return ((bool)(this["AddProductsWithoutName"]));
            }
            set {
                this["AddProductsWithoutName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AddProductsWithoutNameTB {
            get {
                return ((string)(this["AddProductsWithoutNameTB"]));
            }
            set {
                this["AddProductsWithoutNameTB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ProductNameStocks {
            get {
                return ((int)(this["ProductNameStocks"]));
            }
            set {
                this["ProductNameStocks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddOrderToOffersFile {
            get {
                return ((bool)(this["AddOrderToOffersFile"]));
            }
            set {
                this["AddOrderToOffersFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListSettingOffers {
            get {
                return ((string)(this["ListSettingOffers"]));
            }
            set {
                this["ListSettingOffers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MaxOrderQuantity {
            get {
                return ((bool)(this["MaxOrderQuantity"]));
            }
            set {
                this["MaxOrderQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MaxOrderQuantityNumeric {
            get {
                return ((int)(this["MaxOrderQuantityNumeric"]));
            }
            set {
                this["MaxOrderQuantityNumeric"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FileNotInOffersPath {
            get {
                return ((string)(this["FileNotInOffersPath"]));
            }
            set {
                this["FileNotInOffersPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddProductNotInOffers {
            get {
                return ((bool)(this["AddProductNotInOffers"]));
            }
            set {
                this["AddProductNotInOffers"] = value;
            }
        }
    }
}
